name: 'Dispatch: Create Release'

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Stable or pre-release'
        required: true
        type: choice
        options:
          - prerelease
          - release
      version_bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  github_release:
    uses: ./.github/workflows/call.github_release.yml
    secrets: inherit
    with:
      release_mode: ${{ inputs.release_type }}
      version_bump: ${{ inputs.version_bump }}
