name: 'Generic: Platform Uploads'

on:
  workflow_call:
    inputs:
      # File specific params
      file_name:
        description: 'File name'
        required: true
        type: string

      # Common params
      target_tag:
        description: 'Version to upload'
        required: true
        type: string

jobs:
  platform_uploads:
    runs-on: ubuntu-latest
    steps:
    - name: Get release info
      id: release-info
      uses: cardinalby/git-get-release-action@1.2.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ inputs.target_tag }}

    - name: Parse release type
      id: parse-release-type
      run: |
        if [[ "${{ steps.release-info.outputs.prerelease }}" == "true" ]]; then
            echo Setting release_type to Beta
            echo "release_type=Beta" >> $GITHUB_OUTPUT
        else
          echo Setting release_type to Release
            echo "release_type=Release" >> $GITHUB_OUTPUT
        fi
