name: 'Generic: GitHub Release'

on:
  workflow_call:
    inputs:
      # File specific
      file_name:
        description: 'File name'
        required: true
        type: string
      
      # Common params
      release_mode:
        description: 'Release mode'
        required: true
        type: string
      version_bump:
        description: 'Version bump'
        required: false
        type: string
      promote_from:
        description: 'Promote from'
        required: false
        type: string
    outputs:
      release_created:
        description: 'Release created'
        value: ${{ jobs.github_release.outputs.release_created }}
      tag_name:
        description: 'Tag name'
        value: ${{ jobs.github_release.outputs.tag_name }}

jobs:
  github_release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Echo inputs
        run: |
          echo "release_mode: ${{ inputs.release_mode }}"
          echo "version_bump: ${{ inputs.version_bump }}"
          echo "promote_from: ${{ inputs.promote_from }}"

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.promote_from }}

      - name: Create release
        id: release
        if: steps.test.outcome == 'success'
        uses: rymndhng/release-on-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_mode: ${{ inputs.release_mode }}
          version_bump: ${{ inputs.version_bump }}
          promote_from: ${{ inputs.promote_from }}

      - name: Upload release artifact
        if: steps.build.outcome == 'success'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ inputs.file_name }}-${{ steps.release.outputs.tag_name }}.zip
          asset_name: ${{ inputs.file_name }}-${{ steps.release.outputs.tag_name }}.zip
          tag: ${{ steps.release.outputs.tag_name }}
